# Generated by Django 2.2 on 2021-04-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210403_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_end',
        ),
    ]
