# Generated by Django 2.2 on 2021-04-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_choice_question_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question_text',
        ),
        migrations.DeleteModel(
            name='Question_poll',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
